name: setup node
run-name: ${{ github.actor }} Started a process
on:
  push:
    branches:
    - main
jobs:
  setup:
    name: setup node
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3.6.0
      - run: node -v
